name: todotxt_flutter_app
description: A new Flutter project.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.3

  rxdart: 0.27.0
  http: 0.13.3
  intl: 0.17.0
  flutter_slidable: 0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  build_runner:
  flutter_launcher_icons: 0.9.0

flutter:
  uses-material-design: true
